---

- apt: update_cache=yes
       cache_valid_time=3600

- name: Install apache
  apt: pkg=apache2
       state=installed

- name: Create an apache site named {{ sitename }}
  tags: config
  template: src=apache_site_{{ sitename }}.j2
            dest=/etc/apache2/sites-available/{{ sitename }}.conf
            owner=root
            mode=0644
  notify: restart apache2

- name: Enable apache site {{ sitename }}
  command: a2ensite {{ sitename }}
  notify: restart apache2
